name: Gatsby Publish

on:
  # push:
  #   branches:
  #     - master
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.build }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths